### 1.Array creation and Attributes.

In [1]:
# import numpy library.
import numpy as np

In [3]:
#create a 1D  numpy array.

l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [4]:
#create a 1d array of 10 zeros.

arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#create an array of all even integers.
arr = np.arange(10,51)
bool_index = arr % 2 == 0
arr = arr[bool_index]
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
#create a 3*3 matrix with values ranging from 0 to 8.
mat = np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#create a 4*4 identity matrix.
identity_mat = np.eye(4,4)
identity_mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
#create an array of 5 numbers evenly spaced between 0 and 1.
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
#create a 3*4 array  filled with random numbers between 0 and 1.
random_num = np.random.rand(3,4)
random_num

array([[0.19305832, 0.85573404, 0.77827268, 0.97630607],
       [0.96561989, 0.74924684, 0.29235899, 0.18022953],
       [0.22201969, 0.94333943, 0.81240357, 0.43871302]])

In [11]:
#create a 5*5 array with random inteegers from 1 to 100.
arr = np.random.randint(1,100,(5,5))
arr

array([[79, 55,  5,  2,  3],
       [78, 14, 25,  2, 97],
       [25, 98,  4, 41, 45],
       [83, 44, 25, 37, 39],
       [22, 62, 75, 64, 68]], dtype=int32)

In [12]:
#find the shape of given array.
arr = np.arange(25).reshape(5,5)
arr.shape

(5, 5)

In [13]:
#find the data type of above array.
arr.dtype

dtype('int64')

In [14]:
#find the total number of elements.
arr.size

25

In [15]:
#create a array[1,2,3] but make sure its data type is float.
a = np.array([1,2,3], dtype = float)
a
a.dtype


dtype('float64')

In [16]:
#convert the data type of an existing interger array to float.
arr = np.array([1,2,3,4])
new_arr = arr.astype(float)
new_arr.dtype

dtype('float64')

### 2.Indexing and Slicing.

In [17]:
# get the first element.
arr_1d = np.arange(10)
arr_1d[0]

np.int64(0)

In [18]:
#get the last element.
arr_1d[-1]

np.int64(9)

In [19]:
#get the elements from index 2 to 5.
slice = arr_1d[2:6]
slice

array([2, 3, 4, 5])

In [20]:
#get all elements in reverse order.
arr_1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
#get the element at row 1,column 2.
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[1,2]

np.int64(6)

In [22]:
#get entire first row.
arr_2d[0]

array([1, 2, 3])

In [23]:
#get entire second column.
arr_2d[:,1]

array([2, 5, 8])

In [24]:
#extract the sub array [[1,2],[4,5]]
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [25]:
# find all numbers greater than 5.
arr_1d = np.arange(10)
bool_index = arr_1d > 5
arr_1d = arr_1d[bool_index]
arr_1d

array([6, 7, 8, 9])

In [26]:
#select all numbers that are odd.
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
bool_index = arr_2d % 2 != 0
arr_2d = arr_2d[bool_index]
arr_2d

array([1, 3, 5, 7, 9])

In [27]:
#replace all values greater than 5 with 0.
arr_1d = np.arange(10)
arr_1d[arr_1d > 5]= 0
arr_1d

array([0, 1, 2, 3, 4, 5, 0, 0, 0, 0])

In [28]:
#select elements at indices 1,3,7.
arr_1d = np.arange(10)
arr_1d[[1,3,7]]

array([1, 3, 7])

In [29]:
#select the first and third rows.
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [30]:
# 
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = arr_2d.copy()
b[0,0] = 4
b
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
diagonals = np.diag(arr_2d)
diagonals

array([1, 5, 9])

In [32]:
#
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
less = arr_2d[arr_2d[:,0] < 5]
less


array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
#
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
rows = np.array([0,1,2])
cols = np.array([1,0,2])
selected = arr_2d[rows,cols]
selected

array([2, 4, 9])

In [34]:
# reverse the order of rows.
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

### 3.Mathematical and universal functions.

In [35]:
# add array a and b element wise.
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
add = a + b
add

array([ 6,  8, 10, 12])

In [36]:
# multiply array a by 3.
a = np.array([1,2,3,4])
mul = a*3
mul

array([ 3,  6,  9, 12])

In [37]:
#calculate square of every element.
a = np.array([1,2,3,4])
sq = np.square(a)
sq

array([ 1,  4,  9, 16])

In [38]:
#square root of every element in b.
b = np.array([5,6,7,8])
sqt = np.sqrt(b)
sqt

array([2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [39]:
#calculate exponential of every element.
a = np.array([1,2,3,4])
exp = np.exp(a)
exp

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [40]:
#sum of all elements.
a = np.array([1,2,3,4])
sum = np.sum(a)
sum

np.int64(10)

In [41]:
#mean of all elements.
b = np.array([5,6,7,8])
m = np.mean(b)
m

np.float64(6.5)

In [42]:
#maximum value.
a = np.array([1,2,3,4])
max = np.max(a)
max

np.int64(4)

In [43]:
# minimum value in b.
b = np.array([5,6,7,8])
min = np.min(b)
min

np.int64(5)

In [44]:
#find sum of all elements.
mat = np.arange(12).reshape(3,4)
sum = np.sum(mat)
sum

np.int64(66)

In [45]:
# sum of each column.
mat = np.arange(12).reshape(3,4)
sum = np.sum(mat,axis = 0 )
sum

array([12, 15, 18, 21])

In [46]:
#mean of each row.
mat = np.arange(12).reshape(3,4)
m = np.mean(mat,axis=1)
m

array([1.5, 5.5, 9.5])

In [47]:
# minimum value in each row.
mat = np.arange(12).reshape(3,4)
min = np.min(mat,axis = 1)
min

array([0, 4, 8])

In [48]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
new = np.maximum(a,b)
new

array([5, 6, 7, 8])

In [49]:
#round all values to nearest integer.
arr_float = np.array([1.5,2.3,3.8])
r = np.round(arr_float)
r

array([2., 2., 4.])

In [50]:
# calculate standard deviation.
a = np.array([1,2,3,4])
std = np.std(a)
std

np.float64(1.118033988749895)

In [51]:
#calculate cumulative sum of a.
a = np.array([1,2,3,4])
cum = np.cumsum(a)
cum
             

array([ 1,  3,  6, 10])

In [52]:
#compare arrays a and b.
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
equal = a == b
equal

array([False, False, False, False])

In [53]:
a = np.array([1,2,3,4])
com = np.any(a>2)
com


np.True_

In [54]:
 b = np.array([5,6,7,8])
com = np.all(b>4)
com

np.True_

### 4.Key Manipulation techniques

In [55]:
# reshape the array.
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
#flatten the matrix.
matrix = np.array([[1,2],[3,4]])
f = matrix.ravel()
f

array([1, 2, 3, 4])

In [57]:
#Transpose a matrix.
mat = np.arange(15).reshape(3,5)
trans = mat.T
trans

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [58]:
#vertically stack the arrays.
a = np.ones((2,3))
b = np.zeros((2,3))
c = np.vstack((a,b))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
# horizontally stack the arrays.
a = np.ones((2,3))
b = np.zeros((2,3))
c = np.hstack((a,b))
c

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [60]:
#concatenate the arrays.
a = np.ones((2,3))
b = np.zeros((2,3))
c = np.concatenate((a,b))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
# split the arrays in 5 parts.
arr = np.arange(10)
s = np.split(arr,5)
s

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [64]:
# split the array horizontally in 2 parts.
matrix = np.arange(16).reshape(4,4)
arr1,arr2 = np.hsplit(matrix,2)
arr1
arr2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [69]:
arr = np.array([1,2,3,4])
np.insert(arr,2,99)



array([ 1,  2, 99,  3,  4])

In [70]:
arr = np.array([1,2,3,4])
np.append(arr,5)

array([1, 2, 3, 4, 5])

In [71]:
arr = np.array([1,1,1,2,2,2,3,3,3])
np.unique(arr)

array([1, 2, 3])

In [72]:
arr = np.array([1,2,3,])
np.tile(arr,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [73]:
arr = np.array([1,2,3,4])
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

### 5.Broadcasting and conditional logic.

In [75]:
v = np.array([1,2,3])
M = np.ones((4,3))
M + v


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [77]:
arr = np.arange(10)
np.where(arr<5,0,arr)


array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])

In [78]:
arr = np.arange(10)
np.where(arr % 2 ==0,0,1)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [86]:
arr = np.random.randint(25,size = (5,5))
arr = np.where(arr >50,50,arr)
arr

array([[23, 10,  9, 13, 24],
       [19, 22, 23, 15,  0],
       [15, 11,  9,  2, 21],
       [ 7, 12,  6,  7,  8],
       [16,  8, 20,  7, 19]], dtype=int32)

In [90]:
arr = np.arange(10)
m = (arr < 3) | (arr > 8)
arr = arr[m]
arr

array([0, 1, 2, 9])

In [96]:
arr = np.random.randint(1,50,size = (5,5))
m = np.mean(arr)
s = np.std(arr)
n = (arr - m)/(std)
n

array([[ -8.76538647,  -8.76538647,  -0.71554175, -16.81523119,
         -6.97653209],
       [ 18.06742926,   3.7565942 ,  18.06742926, -19.49851276,
         13.5952933 ],
       [-12.34309524,  18.96185645,   4.65102139,  10.91201173,
        -18.60408557],
       [ 13.5952933 , -15.02637681, -16.81523119,  -6.0821049 ,
          7.33430297],
       [  4.65102139, -19.49851276,  13.5952933 ,   5.54544858,
         17.17300207]])

### 6.Statistics,Sorting and Searching.

In [7]:
# create a 1d array of 10 random integers and sort in ascending order.
arr = np.random.randint(1,50,10)
np.sort(arr)

array([ 3,  5,  7, 10, 16, 19, 23, 25, 31, 43], dtype=int32)

In [8]:
# find the indices that would sort an array.
arr = np.array([3,1,4,2])
np.argsort(arr)

array([1, 3, 0, 2])

In [10]:
#find the index of maximum value.
arr = np.array([3,1,4,2])
np.argmax(arr)

np.int64(2)

In [11]:
#index of yhe minimum value.
arr = np.array([3,1,4,2])
np.argmin(arr)

np.int64(1)

In [16]:
arr = np.random.randint(1,50,20).reshape(4,5)
np.argmax(arr,axis=0)

array([3, 2, 1, 3, 0])

In [21]:
arr = np.array([1,2,2,3,3,3,1])
np.unique(arr,return_counts = False)

array([1, 2, 3])

In [22]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.intersect1d(a,b)

array([2, 3])

In [23]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.setdiff1d(a,b)

array([1])

In [2]:
arr = np.array([1,23,45,78,96])
np.percentile(arr,50)


np.float64(45.0)

In [3]:
arr = np.array([1,23,45,78,96])
np.percentile(arr,[25,75])


array([23., 78.])

In [4]:
arr = np.array([1,0,2,0,3])
np.nonzero(arr)

(array([0, 2, 4]),)

In [6]:
a = np.array([1,2,3,4])
b= np.array([4,3,7,9])
np.isin(a,b)

array([False, False,  True,  True])

In [10]:
arr = np.array([10, 55, 30, 8, 90, 45, 62, 20])
sorted_arr = np.sort(arr)[::-1]
top_3 = sorted_arr[:3]
top_3 

array([90, 62, 55])

### 7.Practical Applications(Linear Algebra & I/O)

In [21]:
#create a 2*2 matrix A and a 2*2 matrix B.perform matrix multiplication.
A = np.arange(4).reshape(2,2)
B = np.arange(5,9).reshape(2,2)
C = A @ B
C,


(array([[ 7,  8],
        [31, 36]]),)

In [22]:
# find the inverse of a matrix.
A = np.arange(4).reshape(2,2)
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [23]:
#find the determinant of B.
B = np.arange(5,9).reshape(2,2)
np.linalg.det(B)

np.float64(-1.999999999999999)

In [30]:
arr = np.random.randint(0,50,10)
file = 'my_array.npy'
np.save(file,arr)

In [31]:
data = np.load('my_array.npy')
data

array([ 0, 19, 34, 30, 47, 37, 18, 22, 39, 46], dtype=int32)

In [37]:
arr = np.random.randint(0,50,size = (2,2))
file = 'my_matrix.csv'
data = np.savetxt(file,arr,delimiter= ',',fmt='%d')